-- ~/.config/hypr/hyprland.lua
-- Official LarxOS Hyprland Configuration

hl.config({ autogenerated = false })

-- Defaults
local terminal = "alacritty"
local menu = "rofi -show drun"

-- Input
hl.config({
	input = {
		kb_layout = "us",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
		},
	},
})

-- Keybinds
hl.config({
	binds = {
		{ mod = "SUPER", key = "Q", dispatch = "exec", arg = terminal },
		{ mod = "SUPER", key = "R", dispatch = "exec", arg = menu },
		{ mod = "SUPER", key = "C", dispatch = "killactive" },
		{ mod = "SUPER_M", key = "M", dispatch = "exit" },
	},
})

-- Startup
hl.exec("waybar")
